config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'registrations'}
  get 'static_pages/about'

  get 'static_pages/home'

  get 'static_pages/help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'help' => 'static_pages#help'

  post 'localwikisearch/' => 'local_wiki#search'
  post 'localwikilookup/' => 'local_wiki#lookup'
  post 'localwikisuggest/' => 'local_wiki#suggest'
  post 'localwikicategories/' => 'local_wiki#getcategories'
  get 'localwikicategories/' => 'local_wiki#getcategories'

  post 'localwikivote/' => 'local_wiki#vote'
  post 'localwikiresetsuggestions/' => 'local_wiki#reset_suggestions'
  post 'localwikiroute/' => 'local_wiki#route'

  root 'static_pages#home'

end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    The
    %a(href="wikiexplore.herokuapps.com") WikiExplore App
    by
    %a(href="http://mhoffman.github.io/") Max Hoffmann
  %nav
    %ul
      %li= link_to "About", about_path

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .container.col-lg-12
    = link_to "Wiki Explore", root_path, id: "logo"
    %nav
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to "Help", help_path

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  %script(src="//cdnjs.cloudflare.com/ajax.libs/html5shiv/429/html5.min.js")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title  WikiExplore
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag "http://openlayers.org/en/v3.13.0/css/ol.css"
    = javascript_include_tag "http://openlayers.org/en/v3.12.0/build/ol.js"
    %link{:href=>'https://fonts.googleapis.com/css?family=Open+Sans',:rel=>'stylesheet', :type=>'text/css'}
    %link{:href=>"https://fonts.googleapis.com/icon?family=Material+Icons", :rel=>"stylesheet"}
    = #csrf_meta_tags
    = render 'layouts/shim'
  %body
    = render 'layouts/header'
    .col-lg-12
      .flash-messages
        - flash.each do |message_type, message|
          = content_tag(:div, message, class: "alert alert-#{message_type}")
      /%p.notice
      /  = notice
      /%p.alert
      /  = alert
      = yield
      = javascript_include_tag 'application', 'data-turbolinks-track' => true
      = render 'layouts/footer'
      = debug(params) if Rails.env.development?
      = # current_user